import React from "react";
// Import the hooks generated by your RTK Query API
import { useGetUserTicketsQuery } from "../../redux/slice/usersOperations";

// 1. We use the Ticket interface already defined in your usersOperations file
// If it's not exported there, ensure you export it or define it here
interface Ticket {
  ticket_id: string;
  event_name: string;
  show_date: string;
  total_price: number;
  number_of_tickets: number;
  // Adjust these field names to match your backend's exact JSON keys
}

const MyTickets: React.FC = () => {
  // 2. RTK Query hook handles fetching, loading, and error states automatically
  // No need for useEffect or dispatch!
  const { data, isLoading, isError, error } = useGetUserTicketsQuery();

  // Handle Loading State
  if (isLoading) {
    return (
      <div className="flex justify-center items-center min-h-[400px]">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-slate-800"></div>
        <p className="ml-4 text-slate-600 font-medium">Loading your tickets...</p>
      </div>
    );
  }

  // Handle Error State
  if (isError) {
    return (
      <div className="text-center py-20 px-4">
        <p className="text-red-500 font-semibold">Error loading tickets.</p>
        <p className="text-gray-500 text-sm">{(error as any)?.data?.message || "Please check your connection."}</p>
      </div>
    );
  }

  // Access the array from your UserTicketsResponse interface
  const tickets = data?.userTickets || [];

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 my-6 px-6">
      {tickets.length === 0 ? (
        <div className="col-span-full text-center py-20 bg-gray-50 rounded-xl border-2 border-dashed border-gray-200">
          <p className="text-gray-500 text-lg">You haven't booked any tickets yet.</p>
          <button className="mt-4 text-indigo-600 font-semibold hover:underline">
            Browse Events
          </button>
        </div>
      ) : (
        tickets.map((ticket) => (
          <div key={ticket.ticket_id} className="group relative flex flex-col bg-white shadow-sm hover:shadow-md border border-slate-200 rounded-xl transition-all duration-300">
            <div className="relative h-48 m-2.5 overflow-hidden text-white rounded-lg">
              <img 
                src="https://images.unsplash.com/photo-1540553016722-983e48a2cd10?auto=format&fit=crop&w=800&q=80" 
                alt={ticket.event_name}
                className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
              />
              <div className="absolute top-2 right-2 bg-black/60 backdrop-blur-md px-2 py-1 rounded text-xs">
                ID: {ticket.ticket_id.slice(-6)}
              </div>
            </div>
            
            <div className="p-4">
              <h6 className="mb-2 text-slate-800 text-xl font-bold truncate">
                {ticket.event_name}
              </h6>
              
              <div className="space-y-2 text-slate-600 text-sm">
                <div className="flex justify-between">
                  <span className="text-slate-500">Tickets:</span>
                  <span className="font-semibold text-slate-800">{ticket.number_of_tickets}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Date:</span>
                  <span className="font-semibold text-slate-800">
                    {new Date(ticket.show_date).toLocaleDateString()}
                  </span>
                </div>
                <div className="flex justify-between border-t pt-2 mt-2">
                  <span className="text-slate-500">Total Paid:</span>
                  <span className="font-bold text-green-600">₹{ticket.total_price}</span>
                </div>
              </div>
            </div>
            
            <div className="px-4 pb-4">
              <button 
                className="w-full rounded-lg bg-slate-800 py-2.5 px-4 text-center text-sm font-semibold text-white transition-all shadow-sm hover:bg-slate-700 active:bg-slate-900" 
                type="button"
              >
                View E-Ticket
              </button>
            </div>
          </div>
        ))
      )}
    </div>
  );
}

export default MyTickets;